/* Discoverable touches. Motion only runs when someone interacts. */
(function(){
 'use strict';var reduced=matchMedia('(prefers-reduced-motion: reduce)'),toastTimer;
 function toast(text){var el=document.querySelector('.quiet-toast');if(!el){el=document.createElement('div');el.className='quiet-toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.remove();},2600);}
 function burst(target){if(reduced.matches||document.hidden)return;var r=target.getBoundingClientRect();for(var i=0;i<9;i++){var p=document.createElement('span');p.className='easter-petal';p.textContent=i%3===0?'✳':'❧';p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';document.body.append(p);var a=Math.PI*2*i/9,dx=Math.cos(a)*(45+Math.random()*65),dy=Math.sin(a)*65-35;p.animate([{transform:'translate(-50%,-50%) scale(.4)',opacity:1},{transform:'translate('+dx+'px,'+(dy+80)+'px) rotate('+(i*70)+'deg) scale(.7)',opacity:0}],{duration:900+i*30,easing:'cubic-bezier(.15,.65,.3,1)'}).finished.then(function(){this.remove();}.bind(p));}}
 window.PortfolioDelight={burst:burst,toast:toast};
 document.querySelectorAll('.service-offering').forEach(function(d){d.addEventListener('toggle',function(){document.dispatchEvent(new CustomEvent('portfolio:layout'));});});
 var pen=document.getElementById('writingPen'),desk=pen.closest('.writing-desk'),drag=null,state={x:0,y:0,a:0,vx:0,vy:0,va:0},raf=0,last=0,writeTimer;
 function draw(){pen.style.transform='translate('+state.x+'px,'+state.y+'px) rotate('+(22+state.a)+'deg)';}
 function home(){cancelAnimationFrame(raf);raf=0;if(reduced.matches){state={x:0,y:0,a:0,vx:0,vy:0,va:0};draw();return;}last=0;function tick(t){var dt=last?Math.min((t-last)/1000,.035):1/60;last=t;['x','y','a'].forEach(function(k){var v='v'+k;state[v]+=(-150*state[k]-16*state[v])*dt;state[k]+=state[v]*dt;});draw();if(Math.abs(state.x)+Math.abs(state.y)+Math.abs(state.a)+Math.abs(state.vx)+Math.abs(state.vy)>.5){raf=requestAnimationFrame(tick);}else{state={x:0,y:0,a:0,vx:0,vy:0,va:0};draw();raf=0;}}raf=requestAnimationFrame(tick);}
 function write(){desk.classList.remove('is-writing');requestAnimationFrame(function(){desk.classList.add('is-writing');});document.getElementById('penWhisper').textContent='One more thought, on paper.';clearTimeout(writeTimer);writeTimer=setTimeout(function(){desk.classList.remove('is-writing');document.getElementById('penWhisper').textContent='';},3500);if(!reduced.matches){state.a=-24;state.y=-12;state.vx=35;home();}}
 pen.addEventListener('pointerdown',function(e){if(e.button!==0)return;cancelAnimationFrame(raf);raf=0;drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:state.x,oy:state.y,moved:false};pen.setPointerCapture(e.pointerId);});
 pen.addEventListener('pointermove',function(e){if(!drag)return;var dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;state.x=Math.max(-160,Math.min(100,drag.ox+dx));state.y=Math.max(-150,Math.min(180,drag.oy+dy));state.a=Math.max(-35,Math.min(35,dx*.2));draw();});
 pen.addEventListener('pointerup',function(){if(!drag)return;var moved=drag.moved;drag=null;if(moved)home();else write();});pen.addEventListener('pointercancel',function(){drag=null;home();});pen.addEventListener('click',function(e){if(e.detail===0)write();});
 var logo=document.querySelector('.nav-logo')||document.querySelector('.nav-brand');if(logo)logo.addEventListener('dblclick',function(){burst(logo);toast('Cheh! You found a little extra.');});
 document.querySelectorAll('.service-flower').forEach(function(f){f.addEventListener('click',function(){burst(f);});});
 var signature=document.querySelector('.notebook-sign');if(signature){signature.style.pointerEvents='auto';signature.style.cursor='pointer';signature.addEventListener('dblclick',function(){write();burst(signature);});}
 document.querySelectorAll('.hero-action-ico,.writing-link-ico,.back-to-top').forEach(function(el){el.addEventListener('pointerenter',function(){if(!reduced.matches)el.animate([{transform:'scale(1)'},{transform:'scale(1.2,.85)'},{transform:'scale(.94,1.08)'},{transform:'scale(1)'}],{duration:550,easing:'ease-out'});});});
})();
