export const RPS_CHOICES=['stone','paper','scissors'];
export function rpsResult(you,bot){if(!RPS_CHOICES.includes(you)||!RPS_CHOICES.includes(bot))throw new Error('Invalid hand');return you===bot?'draw':{stone:'scissors',paper:'stone',scissors:'paper'}[you]===bot?'you':'bot';}
export function newRps(){return {you:0,bot:0,round:0,last:null,phase:'ready',pending:null,secret:null};}
export function playRps(state,you,bot){if(state.phase==='over')return state;const result=rpsResult(you,bot),next={...state,round:state.round+1,last:{you,bot,result},pending:null,secret:null,phase:'ready'};if(result==='you')next.you++;if(result==='bot')next.bot++;if(next.you===3||next.bot===3)next.phase='over';return next;}
export function newCricket(){return {innings:1,you:0,bot:0,balls:0,last:null,phase:'ready',pending:null,secret:null,result:null};}
export function cricketBall(state,you,bot){if(state.phase==='over')return state;if(!Number.isInteger(you)||!Number.isInteger(bot)||you<1||you>6||bot<1||bot>6)throw new Error('Invalid cricket number');const next={...state,balls:state.balls+1,pending:null,secret:null,phase:'ready',last:{you,bot,out:you===bot,innings:state.innings}};if(you!==bot)next[state.innings===1?'you':'bot']+=state.innings===1?you:bot;
 if(state.innings===1&&(you===bot||next.balls===6)){next.innings=2;next.balls=0;}else if(state.innings===2){if(next.bot>next.you){next.phase='over';next.result='bot';}else if(you===bot||next.balls===6){next.phase='over';next.result=next.you===next.bot?'draw':'you';}}
 return next;
}
export const WIN_LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
export function gridWinner(cells){for(const [a,b,c]of WIN_LINES)if(cells[a]&&cells[a]!=='draw'&&cells[a]===cells[b]&&cells[a]===cells[c])return cells[a];return cells.every(Boolean)?'draw':null;}
export function newUltimate(){return {cells:Array.from({length:9},()=>Array(9).fill(null)),boards:Array(9).fill(null),forced:null,turn:'X',winner:null,last:null};}
export function ultimateMoves(state){if(state.winner)return [];const boards=state.forced!==null&&!state.boards[state.forced]?[state.forced]:state.boards.map((_,i)=>i).filter(i=>!state.boards[i]);return boards.flatMap(board=>state.cells[board].flatMap((v,cell)=>v?[]:[{board,cell}]));}
export function ultimateMove(state,board,cell){if(!ultimateMoves(state).some(m=>m.board===board&&m.cell===cell))throw new Error('Illegal Ultimate move');const next={...state,cells:state.cells.map(c=>c.slice()),boards:state.boards.slice(),last:{board,cell,player:state.turn}};next.cells[board][cell]=state.turn;next.boards[board]=gridWinner(next.cells[board]);next.winner=gridWinner(next.boards);next.forced=next.boards[cell]?null:cell;next.turn=state.turn==='X'?'O':'X';return next;}
function ultimateScore(state){if(state.winner)return state.winner==='O'?100000:state.winner==='X'?-100000:0;let value=0;const weights=[3,2,3,2,4,2,3,2,3];for(let i=0;i<9;i++){if(state.boards[i]){value+=state.boards[i]==='O'?120*weights[i]:state.boards[i]==='X'?-120*weights[i]:0;continue;}for(const line of WIN_LINES){const a=line.map(j=>state.cells[i][j]),x=a.filter(v=>v==='X').length,o=a.filter(v=>v==='O').length;if(!x)value+=(o===2?12:o===1?2:0)*weights[i];if(!o)value-=(x===2?14:x===1?2:0)*weights[i];}}for(const line of WIN_LINES){const a=line.map(j=>state.boards[j]);if(a.includes('draw'))continue;const x=a.filter(v=>v==='X').length,o=a.filter(v=>v==='O').length;if(!x)value+=o===2?900:o===1?70:0;if(!o)value-=x===2?1000:x===1?70:0;}return value;}
export function ultimateChoice(state,random=Math.random){const moves=ultimateMoves(state);if(!moves.length)return null;let best=-Infinity,chosen=moves[0];for(const m of moves){const next=ultimateMove(state,m.board,m.cell);let value=ultimateScore(next);if(!next.winner){const replies=ultimateMoves(next);let worst=Infinity;for(const r of replies)worst=Math.min(worst,ultimateScore(ultimateMove(next,r.board,r.cell)));value=worst;}value+=random()*.2;if(value>best){best=value;chosen=m;}}return chosen;}
