import {Chess} from './vendor/chess.mjs';
import {newDeck,handValue,cardResult,newPens,TABLE,stepPens,pensMoving,shootPen,chessChoice,CHESS_PROFILE} from './game-core.mjs';
import {GAME_IDS,SAVE_VERSION,createGameStore,validSave} from './game-save.mjs';
import {RPS_CHOICES,newRps,playRps,newCricket,cricketBall,newUltimate,ultimateMoves,ultimateMove,ultimateChoice} from './extra-games.mjs';
import {GAME_GUIDES,penResultFromSave,outcomeCopy} from './game-feedback.mjs';
import {chessPieceSVG} from './chess-pieces.mjs';
import {freshClock,validClock,clockTurn,advanceClock,completeClockMove,formatClock,chessTimeoutResult} from './game-clock.mjs';
const $=id=>document.getElementById(id), dialog=$('playroomDialog'),open=$('playroomOpen'),config=window.PortfolioPlayConfig||{},reduced=matchMedia('(prefers-reduced-motion: reduce)');
let active='pens',tokens=0,priorOverflow='',timer=null,generation=0,roundPaid=Object.fromEntries(GAME_IDS.map(g=>[g,false])),hydrated=false,saveQueue=Promise.resolve(),store=createGameStore();
try{tokens=Math.max(0,Math.min(99999,Number(localStorage.getItem('shri-lotus-tokens'))||0));}catch{}
function showTokens(){$('playTokens').textContent=`✳ ${tokens} lotus token${tokens===1?'':'s'}`;}showTokens();
function say(mood){const expression=config.expressions?.[mood]||config.expressions?.greeting||{line:'Your move, friend.'};$('botLine').textContent=expression.lines?expression.lines[Math.floor(Math.random()*expression.lines.length)]:expression.line;$('botExpression').src=expression.image||config.botAvatar||'assets/img/shri-bot-pixel.png';$('botExpression').parentElement.dataset.mood=mood;}
const outcomes={},settlements={},clocks={chess:freshClock()};let clockLast=0,clockPersist=0,clockSettling=false;
const stages={pens:'penTable',chess:'chessBoard',cards:null,rps:null,cricket:null,ultimate:'ultimateBoard'};
for(const game of GAME_IDS){const panel=$('panel'+game[0].toUpperCase()+game.slice(1)),board=stages[game]?$(stages[game]):panel.querySelector(game==='cards'?'.card-table':game==='rps'?'.rps-arena':'.cricket-ground'),stage=document.createElement('div');stage.className=`game-stage game-stage--${game}`;board.before(stage);stage.append(board);const overlay=document.createElement('div');overlay.className='game-result';overlay.hidden=true;overlay.setAttribute('role','region');overlay.setAttribute('aria-label','Match result');overlay.innerHTML=`<div class="game-result-card"><span class="result-flower" aria-hidden="true">✳</span><p class="result-eyebrow">MATCH COMPLETE</p><h3 class="result-title"></h3><p class="result-score"></p><p class="result-detail"></p><p class="result-reward"></p><button type="button" class="result-rematch" data-rematch="${game}">Play again <span aria-hidden="true">↻</span></button><button type="button" class="result-view" data-view-result="${game}">View the board</button></div>`;stage.append(overlay);const recap=document.createElement('button');recap.type='button';recap.className='result-reopen';recap.hidden=true;recap.dataset.reopenResult=game;stage.append(recap);}
function resultState(game){return game==='cards'?{you:handValue(yourHand),bot:handValue(botHand)}:game==='rps'?rps:game==='cricket'?cricket:game==='ultimate'?ultimate:{};}
function showResult(game,result,celebrate=false){const panel=$('panel'+game[0].toUpperCase()+game.slice(1)),stage=panel.querySelector('.game-stage'),overlay=stage.querySelector('.game-result'),copy=outcomeCopy(game,result,resultState(game));const reason=settlements[game]?.reason;if(reason==='timeout')copy.detail=result==='draw'?'Time ran out, but the opponent has only a king and cannot deliver mate.':result==='you'?'Shri ran out of time. You take the match.':'Your clock ran out. Another round?';if(reason==='resigned')copy.detail='You resigned. Shri takes this game.';if(reason==='agreed')copy.detail='Draw agreed. Good game, friend.';stage.dataset.result=result;for(const key of ['title','score','detail','reward'])overlay.querySelector('.result-'+key).textContent=copy[key];overlay.querySelector('.result-eyebrow').textContent=result==='you'?'VICTORY · NICELY PLAYED':result==='bot'?'SHRI TAKES THE ROUND':'MATCH DRAWN';stage.querySelector('.result-reopen').textContent=copy.title+' · See result ↗';if(outcomes[game]!==result){overlay.hidden=false;stage.querySelector('.result-reopen').hidden=true;}outcomes[game]=result;overlay.classList.toggle('is-new-result',celebrate&&!reduced.matches);if(active===game&&dialog.open){$('playTurn').textContent='Match complete';if(celebrate)requestAnimationFrame(()=>overlay.querySelector('.result-rematch').focus({preventScroll:true}));}}
function clearResult(game){delete outcomes[game];delete settlements[game];if(game==='chess')clocks.chess=freshClock(clocks.chess.enabled);clockLast=performance.now();const stage=$('panel'+game[0].toUpperCase()+game.slice(1)).querySelector('.game-stage');delete stage.dataset.result;stage.querySelector('.game-result').hidden=true;stage.querySelector('.result-reopen').hidden=true;}
function finish(game,result,reason='natural'){settlements[game]||={result,reason};showResult(game,result,hydrated&&!roundPaid[game]&&dialog.open&&active===game);const statusId={pens:'penStatus',chess:'chessStatus',cards:'cardStatus',rps:'rpsStatus',cricket:'cricketStatus',ultimate:'ultimateStatus'}[game];$(statusId).textContent=outcomeCopy(game,result,resultState(game)).title;stopGameControls(game);if(roundPaid[game])return;roundPaid[game]=true;if(result==='you'){tokens++;showTokens();say('losing');$('botPrize').classList.remove('is-won');if(!reduced.matches){requestAnimationFrame(()=>$('botPrize').classList.add('is-won'));window.PortfolioDelight?.burst($('botPrize'));}}else say(result==='draw'?'draw':'winning');save();}
dialog.addEventListener('click',e=>{const replay=e.target.closest('[data-rematch]'),view=e.target.closest('[data-view-result]'),reopen=e.target.closest('[data-reopen-result]');if(replay){dialog.querySelector(`[data-reset="${replay.dataset.rematch}"]`).click();$('panel'+replay.dataset.rematch[0].toUpperCase()+replay.dataset.rematch.slice(1)).querySelector('canvas,button:not(:disabled):not([data-reset])')?.focus({preventScroll:true});}if(view||reopen){const game=view?.dataset.viewResult||reopen.dataset.reopenResult,stage=$('panel'+game[0].toUpperCase()+game.slice(1)).querySelector('.game-stage');stage.querySelector('.game-result').hidden=!!view;stage.querySelector('.result-reopen').hidden=!view;(view?stage.querySelector('.result-reopen'):stage.querySelector('.result-rematch')).focus({preventScroll:true});}});
function turnLabel(){if(outcomes[active])return 'Match complete';if(active==='chess')return chess.turn()==='b'?'Shri is thinking…':'Your move · White';if(active==='pens')return penPhase==='moving'?'Pens in motion…':penTurn==='bot'?'Shri’s flick':'Your flick';if(active==='cards')return cardPhase==='bot'?'Shri’s hand':'Your hand';if(active==='rps')return rps.phase==='reveal'?'Hands out…':'Your choice · first to 3';if(active==='cricket')return cricket.phase==='ball'?'Hands out…':cricket.innings===1?'You’re batting':'You’re bowling';return ultimate.turn==='O'?'Shri is thinking…':'Your move · X';}
function updateTurn(){if(hydrated){$('playTurn').textContent=turnLabel();renderClock();}}
function later(fn,delay=650){clearTimeout(timer);const g=generation;timer=setTimeout(()=>{timer=null;if(dialog.open&&g===generation&&!settlements[active]){settleClock();if(!settlements[active])fn();}},delay);}
function cancelPending(){clearTimeout(timer);timer=null;generation++;}
open.addEventListener('click',()=>{document.dispatchEvent(new CustomEvent('portfolio:before-dialog'));priorOverflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';document.dispatchEvent(new CustomEvent('portfolio:dialog',{detail:{open:true}}));say('greeting');resume();});
$('playroomClose').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
dialog.addEventListener('close',()=>{clockLast=0;save();cancelPending();cancelAnimationFrame(penRaf);penRaf=0;penLast=0;aim=null;document.body.style.overflow=priorOverflow;document.dispatchEvent(new CustomEvent('portfolio:dialog',{detail:{open:false}}));open.focus({preventScroll:true});});
const tabs=[...dialog.querySelectorAll('[data-game]')];
function switchGame(game){settleClock();cancelPending();cancelAnimationFrame(penRaf);penRaf=0;penLast=0;aim=null;active=game;clockLast=performance.now();$('gameHelp').open=false;$('gameHelpTitle').textContent=GAME_GUIDES[game].name;$('gameHelpBody').textContent=GAME_GUIDES[game].rules;tabs.forEach(b=>{const chosen=b.dataset.game===game;b.setAttribute('aria-selected',chosen);b.tabIndex=chosen?0:-1;});GAME_IDS.forEach(g=>$('panel'+g[0].toUpperCase()+g.slice(1)).hidden=g!==game);say('greeting');resume();save();}
tabs.forEach((b,i)=>{b.addEventListener('click',()=>switchGame(b.dataset.game));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();switchGame(tabs[next].dataset.game);tabs[next].focus();}});});
dialog.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',e=>{cancelPending();const g=b.dataset.reset;clearResult(g);roundPaid[g]=false;if(g==='pens')resetPens();if(g==='chess')resetChess();if(g==='cards')resetCards();if(g==='rps')resetRps();if(g==='cricket')resetCricket();if(g==='ultimate')resetUltimate();say('rematch');save();if(e.detail) $('panel'+g[0].toUpperCase()+g.slice(1)).querySelector('canvas,button:not(:disabled):not([data-reset])')?.focus({preventScroll:true});}));
function resume(){clockLast=performance.now();if(settlements[active]){renderSavedGame(active);finish(active,settlements[active].result,settlements[active].reason);updateTurn();return;}if(active==='pens'){drawPens();if(penPhase==='over')finish('pens',penResult);if(penPhase==='moving')animatePens();else if(penTurn==='bot'&&penPhase!=='over')botFlick();}if(active==='chess'){renderChess();if(chess.turn()==='b'&&!chess.isGameOver())botChess();}if(active==='cards'){renderCards();if(cardPhase==='over')finish('cards',cardResult(yourHand,botHand));if(cardPhase==='bot')botCards();}if(active==='rps'){renderRps();if(rps.phase==='reveal')resolveRps();}if(active==='cricket'){renderCricket();if(cricket.phase==='ball')resolveCricket();}if(active==='ultimate'){renderUltimate();if(ultimate.turn==='O'&&!ultimate.winner)botUltimate();}updateTurn();}
/* Chess: the rules library validates every move; the bot searches legal replies. */
let chess=new Chess(),selected=null,promotion=null,lastMove=null;
const pieceName={k:'king',q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn'};
function resetChess(){$('chessDraw').disabled=$('chessResign').disabled=false;$('chessResignConfirm').hidden=true;chess=new Chess();selected=null;promotion=null;lastMove=null;renderChess();}
function renderChess(){const focusedSquare=document.activeElement?.dataset.square;const legal=selected?chess.moves({square:selected,verbose:true}):[];let html='';
 const board=chess.board();for(let r=0;r<8;r++)for(let f=0;f<8;f++){const p=board[r][f],sq=String.fromCharCode(97+f)+(8-r),dest=legal.some(m=>m.to===sq);html+=`<button type="button" class="chess-square ${(r+f)%2?'is-dark':''} ${p?'is-piece':''} ${dest?'is-legal':''} ${sq===selected?'is-selected':''} ${lastMove&&(lastMove.from===sq||lastMove.to===sq)?'is-last':''} ${p?.type==='k'&&p.color===chess.turn()&&chess.isCheck()?'is-check':''}" data-square="${sq}" data-white="${p?.color==='w'}" aria-label="${f===0||r===7?`${f===0?8-r:''}${r===7?String.fromCharCode(97+f):''}, `:''}${sq}${p?', '+(p.color==='w'?'white ':'black ')+pieceName[p.type]:', empty'}${dest?', legal destination':''}" aria-pressed="${sq===selected}">${p?chessPieceSVG(p):''}${f===0||r===7?`<small aria-hidden="true">${f===0?8-r:''}${r===7?String.fromCharCode(97+f):''}</small>`:''}</button>`;}
 $('chessBoard').innerHTML=html;if(focusedSquare)$('chessBoard').querySelector(`[data-square="${focusedSquare}"]`)?.focus({preventScroll:true});const history=chess.history();$('chessMoves').innerHTML='';for(let i=0;i<history.length;i+=2){const li=document.createElement('li');li.textContent=history[i]+' '+(history[i+1]||'…');$('chessMoves').append(li);}$('chessMoves').scrollTop=$('chessMoves').scrollHeight;
 $('chessPromotion').hidden=!promotion;
 if(settlements.chess){$('chessStatus').textContent=outcomeCopy('chess',settlements.chess.result,{}).title;}else if(chess.isCheckmate()){$('chessStatus').textContent=chess.turn()==='b'?'Checkmate. You win a lotus!':'Checkmate. Shri takes this one.';finish('chess',chess.turn()==='b'?'you':'bot');}else if(chess.isGameOver()){$('chessStatus').textContent='A draw. Good minds think alike.';finish('chess','draw');}else $('chessStatus').textContent=promotion?'Choose a promotion piece.':chess.turn()==='b'?'Shri is thinking…':chess.isCheck()?'Check. Protect your king.':'Your move. You play white.';
}
function doChess(move){if(!clockMove('chess','you'))return;try{lastMove=chess.move(move);}catch{return;}selected=null;promotion=null;renderChess();save();if(!chess.isGameOver()&&chess.turn()==='b')botChess();}
function botChess(){say('thinking');later(()=>{const move=chessChoice(chess,CHESS_PROFILE.depth,{profile:'casual1100'});if(move&&clockMove('chess','bot')){lastMove=chess.move(move);renderChess();save();if(!chess.isGameOver())say(lastMove.captured?'confident':'surprised');}},550);}
$('chessBoard').addEventListener('click',e=>{const b=e.target.closest('[data-square]');if(!b||settlements.chess||chess.turn()!=='w'||chess.isGameOver()||promotion)return;const sq=b.dataset.square,p=chess.get(sq);if(selected){const choices=chess.moves({square:selected,verbose:true}).filter(m=>m.to===sq);if(choices.length){if(choices[0].promotion){promotion={from:selected,to:sq};renderChess();save();$('chessPromotion').querySelector('button').focus();return;}doChess({from:selected,to:sq});return;}}selected=p?.color==='w'?(selected===sq?null:sq):null;renderChess();$('chessBoard').querySelector(`[data-square="${sq}"]`)?.focus({preventScroll:true});});
$('chessBoard').addEventListener('keydown',e=>{const b=e.target.closest('[data-square]');if(!b)return;const keys={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8};if(!(e.key in keys))return;e.preventDefault();const buttons=[...$('chessBoard').querySelectorAll('button')],idx=buttons.indexOf(b),to=idx+keys[e.key];if(to>=0&&to<64&&(Math.abs(keys[e.key])===8||Math.floor(to/8)===Math.floor(idx/8)))buttons[to].focus();});
$('chessPromotion').addEventListener('click',e=>{const b=e.target.closest('[data-promote]');if(b&&promotion)doChess({...promotion,promotion:b.dataset.promote});});
/* Twenty-one: a shuffled full deck, flexible aces, and a dealer drawing to 17. */
let deck=[],yourHand=[],botHand=[],cardPhase='you';
function cardHTML(card,hidden=false){return hidden?'<div class="playing-card is-face-down" role="img" aria-label="Face-down card"></div>':`<div class="playing-card ${['♥','♦'].includes(card.suit)?'is-red':''}" role="img" aria-label="${card.rank} ${card.suit}">${card.rank}<span>${card.suit}</span><i>${card.rank}</i></div>`;}
function renderCards(){const reveal=cardPhase==='over';$('yourHand').innerHTML=yourHand.map(c=>cardHTML(c)).join('');$('botHand').innerHTML=botHand.map((c,i)=>cardHTML(c,i===1&&!reveal)).join('');$('yourTotal').textContent=handValue(yourHand);$('botTotal').textContent=reveal?handValue(botHand):'?';$('cardHit').disabled=$('cardStand').disabled=cardPhase!=='you';save();}
function resetCards(){deck=newDeck();yourHand=[deck.pop(),deck.pop()];botHand=[deck.pop(),deck.pop()];cardPhase='you';$('cardStatus').textContent='Hit or stay. Shri draws to 17.';renderCards();if(handValue(yourHand)===21){cardPhase='bot';renderCards();if(dialog.open&&active==='cards')botCards();}}
function finishCards(){cardPhase='over';const result=cardResult(yourHand,botHand);renderCards();$('cardStatus').textContent=result==='you'?'You win. A lotus for your collection.':result==='draw'?'A tie. Keep your lucky charm for the next hand.':handValue(yourHand)>21?'Over 21. Shri wins this hand.':'Shri takes this hand.';finish('cards',result);}
function botCards(){say('thinking');later(()=>{if(handValue(yourHand)<=21&&handValue(botHand)<17){if(!clockMove('cards','bot'))return;botHand.push(deck.pop());renderCards();botCards();}else{if(!clockMove('cards','bot'))return;finishCards();}},550);}
$('cardHit').addEventListener('click',()=>{if(cardPhase!=='you'||!clockMove('cards','you'))return;yourHand.push(deck.pop());renderCards();if(handValue(yourHand)>21)finishCards();else if(handValue(yourHand)===21){cardPhase='bot';renderCards();botCards();}else say('surprised');});
$('cardStand').addEventListener('click',()=>{if(cardPhase!=='you'||!clockMove('cards','you'))return;cardPhase='bot';renderCards();$('cardStatus').textContent='Let’s see Shri’s hand…';botCards();});
/* Pen fight: capsule collisions transfer momentum and spin. The desk has no rails. */
const canvas=$('penTable'),ctx=canvas.getContext('2d');let pens=newPens(),penTurn='you',penPhase='ready',aim=null,penRaf=0,penLast=0,shots=0,penResult=null;
function resetPens(){cancelAnimationFrame(penRaf);penRaf=0;penLast=0;pens=newPens();penTurn='you';penPhase='ready';aim=null;shots=0;penResult=null;$('penStatus').textContent='Your turn. Make the first flick.';$('penFlick').disabled=false;drawPens();}
function penPoint(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*TABLE.width,y:(e.clientY-r.top)/r.height*TABLE.height};}
function drawPens(){ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,640,420);ctx.fillStyle='#e8d4b1';ctx.fillRect(0,0,640,420);ctx.strokeStyle='#b695622e';ctx.lineWidth=1;for(let y=20;y<420;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(160,y-7,440,y+8,640,y);ctx.stroke();}ctx.strokeStyle='#a7875780';ctx.strokeRect(14,14,612,392);
 // Delicate flowers in the four corners of the school desk.
 for(const [x,y]of [[33,33],[607,33],[33,387],[607,387]]){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#a7875744';for(let a=0;a<8;a++){ctx.rotate(Math.PI/4);ctx.beginPath();ctx.ellipse(0,7,3,8,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
 for(const p of pens){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.shadowColor='#523b3c35';ctx.shadowBlur=8;ctx.shadowOffsetY=5;ctx.fillStyle=p.id==='you'?'#643747':'#b48a48';ctx.beginPath();ctx.roundRect(-52,-9,104,18,8);ctx.fill();ctx.shadowColor='transparent';ctx.fillStyle=p.id==='you'?'#e5c58c':'#4f3438';ctx.fillRect(20,-9,4,18);ctx.fillRect(-43,-9,3,18);ctx.beginPath();ctx.moveTo(52,-7);ctx.lineTo(65,0);ctx.lineTo(52,7);ctx.closePath();ctx.fill();ctx.fillStyle='#fcf0d5';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText(p.id==='you'?'YOU':'SHRI',-6,3);ctx.strokeStyle='#ffffff35';ctx.beginPath();ctx.moveTo(-36,-4);ctx.lineTo(16,-4);ctx.stroke();ctx.restore();}
 if(penTurn==='you'&&penPhase==='ready'){const p=pens[0],angle=Number($('penAngle').value)*Math.PI/180,power=Number($('penPower').value);let dx=Math.cos(angle)*power*1.15,dy=Math.sin(angle)*power*1.15;if(aim){dx=p.x-aim.x;dy=p.y-aim.y;}const length=Math.min(145,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);ctx.setLineDash([5,6]);ctx.strokeStyle='#643747aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.cos(a)*length,p.y+Math.sin(a)*length);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#643747';ctx.beginPath();const x=p.x+Math.cos(a)*length,y=p.y+Math.sin(a)*length;ctx.moveTo(x,y);ctx.lineTo(x-9*Math.cos(a-.5),y-9*Math.sin(a-.5));ctx.lineTo(x-9*Math.cos(a+.5),y-9*Math.sin(a+.5));ctx.closePath();ctx.fill();}
}
function endPens(result){penPhase='over';penResult=result;$('penFlick').disabled=true;$('penStatus').textContent=result==='you'?'Shri’s pen is off the desk. You win a lotus!':result==='draw'?'Both pens went flying. Let’s call that a draw.':'Your pen left the desk. Shri takes this round.';finish('pens',result);drawPens();}
function animatePens(){if(penRaf||!dialog.open||active!=='pens'||document.hidden)return;penLast=0;function frame(t){penRaf=0;if(!dialog.open||active!=='pens'||document.hidden||settlements.pens)return;let remaining=penLast?Math.min((t-penLast)/1000,.05):1/60;penLast=t;while(remaining>0){const dt=Math.min(remaining,1/120),result=stepPens(pens,dt);remaining-=dt;if(result){endPens(result);penLast=0;return;}}drawPens();if(t-(animatePens.lastSave||0)>500){save(true);animatePens.lastSave=t;}if(pensMoving(pens))penRaf=requestAnimationFrame(frame);else{penPhase='ready';penLast=0;penTurn=penTurn==='you'?'bot':'you';save();if(shots>=20){endPens('draw');return;}if(penTurn==='bot'){botFlick();}else{$('penFlick').disabled=false;$('penStatus').textContent='Your turn. Find your angle.';say('confident');drawPens();}}}penRaf=requestAnimationFrame(frame);}
function flick(dx,dy){if(penPhase!=='ready'||settlements.pens)return;const side=penTurn;const p=pens[penTurn==='you'?0:1];if(Math.hypot(dx,dy)<8||!clockMove('pens',side)||!shootPen(p,dx,dy))return;shots++;penPhase='moving';aim=null;$('penFlick').disabled=true;$('penStatus').textContent=penTurn==='you'?'Your pen is in motion…':'Shri makes his move…';save();animatePens();}
function botFlick(){say('thinking');$('penFlick').disabled=true;$('penStatus').textContent='Shri is lining up a shot…';later(()=>{const a=pens[1],b=pens[0],angle=Math.atan2(b.y-a.y,b.x-a.x)+(Math.random()-.5)*.12,distance=Math.hypot(a.x-b.x,a.y-b.y),pull=Math.min(126,Math.max(66,distance*.32));flick(Math.cos(angle)*pull,Math.sin(angle)*pull);},800);}
canvas.addEventListener('pointerdown',e=>{if(penTurn!=='you'||penPhase!=='ready')return;const pt=penPoint(e);if(Math.hypot(pt.x-pens[0].x,pt.y-pens[0].y)>80)return;canvas.setPointerCapture(e.pointerId);aim=pt;drawPens();});canvas.addEventListener('pointermove',e=>{if(!aim)return;aim=penPoint(e);drawPens();});canvas.addEventListener('pointerup',e=>{if(!aim)return;const p=pens[0],pt=penPoint(e);aim=null;flick(p.x-pt.x,p.y-pt.y);drawPens();});canvas.addEventListener('pointercancel',()=>{aim=null;drawPens();});
$('penFlick').addEventListener('click',()=>{if(penTurn!=='you')return;const a=Number($('penAngle').value)*Math.PI/180,p=Number($('penPower').value)*1.15;flick(Math.cos(a)*p,Math.sin(a)*p);});['penAngle','penPower'].forEach(id=>$(id).addEventListener('input',()=>{drawPens();save();}));
canvas.addEventListener('keydown',e=>{if(penTurn!=='you'||penPhase!=='ready')return;if(e.key===' '){e.preventDefault();$('penFlick').click();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();$('penAngle').value=Math.max(-180,Math.min(180,Number($('penAngle').value)+(['ArrowLeft','ArrowUp'].includes(e.key)?-5:5)));drawPens();}else if(['+','=','-'].includes(e.key)){e.preventDefault();$('penPower').value=Math.max(15,Math.min(100,Number($('penPower').value)+(e.key==='-'?-5:5)));drawPens();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clockLast=0;save();cancelAnimationFrame(penRaf);penRaf=0;penLast=0;cancelPending();}else if(dialog.open)resume();});

/* Hands are committed before a visitor chooses, then revealed together. */
const handGlyph={stone:'✊',paper:'✋',scissors:'✌️'},randomHand=()=>RPS_CHOICES[Math.floor(Math.random()*3)],randomRun=()=>1+Math.floor(Math.random()*6);
let rps=newRps(),cricket=newCricket(),ultimate=newUltimate();
function resetRps(){rps=newRps();rps.secret=randomHand();renderRps();}
function renderRps(){$('panelRps').classList.toggle('is-revealing',rps.phase==='reveal');const l=rps.last;$('rpsYourHand').textContent=rps.phase==='reveal'?'✊':l?handGlyph[l.you]:'✊';$('rpsBotHand').textContent=rps.phase==='reveal'?'✊':l?handGlyph[l.bot]:'✊';$('rpsYourScore').textContent=rps.you;$('rpsBotScore').textContent=rps.bot;dialog.querySelectorAll('[data-rps]').forEach(b=>{b.disabled=rps.phase!=='ready';b.classList.toggle('is-chosen',b.dataset.rps===(rps.pending||rps.last?.you));});$('rpsStatus').textContent=rps.phase==='over'?(rps.you===3?'You take the match. A lotus for you!':'Shri takes the match. Rematch?'):rps.phase==='reveal'?'Stone… paper… scissors…':l?(l.result==='draw'?'Same wavelength. Go again.':l.result==='you'?'Your point. First to three.':'Shri’s point. Your next move?'):'Pick your hand. Shri has already picked his.';if(rps.phase==='over')finish('rps',rps.you===3?'you':'bot');}
function resolveRps(){say('thinking');later(()=>{if(!clockMove('rps','bot'))return;rps=playRps(rps,rps.pending,rps.secret);if(rps.phase!=='over')rps.secret=randomHand();renderRps();if(rps.phase!=='over')say(rps.last.result==='you'?'surprised':rps.last.result==='draw'?'draw':'confident');save();},650);}
dialog.querySelectorAll('[data-rps]').forEach(b=>b.addEventListener('click',()=>{if(rps.phase!=='ready'||!clockMove('rps','you'))return;rps.pending=b.dataset.rps;rps.phase='reveal';renderRps();save();resolveRps();}));
function resetCricket(){cricket=newCricket();cricket.secret=randomRun();renderCricket();}
function renderCricket(){$('panelCricket').classList.toggle('is-revealing',cricket.phase==='ball');const l=cricket.last;$('cricketYou').textContent=cricket.you;$('cricketBot').textContent=cricket.bot;$('cricketInnings').textContent=cricket.phase==='over'?'Match complete':cricket.innings===1?'Your innings':'Shri’s innings';$('cricketBalls').textContent=`${cricket.balls} / 6 balls`;$('cricketTarget').textContent=cricket.innings===1?'One wicket · six balls':cricket.phase==='over'?`Target ${cricket.you+1}`:`Target ${cricket.you+1} · ${Math.max(0,cricket.you+1-cricket.bot)} to win`;$('cricketBallTrack').innerHTML=Array.from({length:6},(_,i)=>`<i class="${i<cricket.balls?'is-bowled':''}"></i>`).join('');$('cricketBallCall').textContent=cricket.phase==='ball'?'Hands out…':l?.out?'WICKET!':l?`${l.innings===1?l.you:l.bot} RUN${(l.innings===1?l.you:l.bot)===1?'':'S'}`:'Your innings starts here';$('cricketBallCall').dataset.wicket=String(!!l?.out&&cricket.phase!=='ball');const teams=$('panelCricket').querySelectorAll('.cricket-score>div');teams[0].classList.toggle('is-batting',cricket.innings===1&&cricket.phase!=='over');teams[2].classList.toggle('is-batting',cricket.innings===2&&cricket.phase!=='over');$('cricketYourHand').textContent=cricket.phase==='ball'?'…':l?l.you:'—';$('cricketBotHand').textContent=cricket.phase==='ball'?'…':l?l.bot:'—';dialog.querySelectorAll('[data-cricket]').forEach(b=>{b.disabled=cricket.phase!=='ready';b.classList.toggle('is-chosen',Number(b.dataset.cricket)===(cricket.pending||cricket.last?.you));});$('cricketStatus').textContent=cricket.phase==='over'?(cricket.result==='you'?'You defend your total. A lotus for you!':cricket.result==='draw'?'Scores level. An honourable draw.':'Shri chases it down. Rematch?'):cricket.phase==='ball'?'Both hands are coming out…':l?.out?(l.innings===1?'Out! Now defend your total. Pick a number to bowl.':'Out!'):l?`${l.innings===1?l.you:l.bot} runs. ${cricket.innings===1?'Pick your next shot.':'Pick your next delivery.'}`:'Choose 1–6. Matching hands means out.';if(cricket.phase==='over')finish('cricket',cricket.result);}
function resolveCricket(){say('thinking');later(()=>{if(!clockMove('cricket','bot'))return;cricket=cricketBall(cricket,cricket.pending,cricket.secret);if(cricket.phase!=='over')cricket.secret=randomRun();renderCricket();if(cricket.phase!=='over')say(cricket.last.out?'surprised':'confident');save();},650);}
dialog.querySelectorAll('[data-cricket]').forEach(b=>b.addEventListener('click',()=>{if(cricket.phase!=='ready'||!clockMove('cricket','you'))return;cricket.pending=Number(b.dataset.cricket);cricket.phase='ball';renderCricket();save();resolveCricket();}));
function resetUltimate(){ultimate=newUltimate();renderUltimate();}
function renderUltimate(){const legal=ultimateMoves(ultimate),allowed=new Set(legal.map(m=>m.board));$('ultimateBoard').innerHTML=ultimate.cells.map((cells,b)=>`<div class="ultimate-mini ${allowed.has(b)?'is-active':''} ${ultimate.boards[b]?'is-closed':''}" role="group" aria-label="Small board ${b+1}"><small class="ultimate-number" aria-hidden="true">${b+1}</small>${cells.map((v,c)=>`<button type="button" data-ultimate-board="${b}" data-cell="${c}" ${v||ultimate.boards[b]||!allowed.has(b)||ultimate.turn!=='X'?'disabled':''} class="${v==='O'?'is-bot':''} ${ultimate.last?.board===b&&ultimate.last.cell===c?'is-last':''}" aria-label="Board ${b+1}, cell ${c+1}${v?', '+v:''}">${v||''}</button>`).join('')}${ultimate.boards[b]?`<span class="ultimate-won" aria-label="${ultimate.boards[b]==='draw'?'Drawn board':ultimate.boards[b]+' won this board'}">${ultimate.boards[b]==='draw'?'—':ultimate.boards[b]}</span>`:''}</div>`).join('');$('ultimateStatus').textContent=ultimate.winner?(ultimate.winner==='X'?'Three boards in a row. You win a lotus!':ultimate.winner==='O'?'Shri connects three. Another round?':'All boards filled. A draw.'):(ultimate.turn==='O'?'Shri is thinking… ': 'Your move. ')+(ultimate.forced===null?'Choose any open board.':`Play in board ${ultimate.forced+1}.`);if(ultimate.winner)finish('ultimate',ultimate.winner==='X'?'you':ultimate.winner==='O'?'bot':'draw');}
function botUltimate(){say('thinking');later(()=>{const m=ultimateChoice(ultimate);if(m&&clockMove('ultimate','bot')){ultimate=ultimateMove(ultimate,m.board,m.cell);renderUltimate();save();if(!ultimate.winner)say('confident');}},650);}
$('ultimateBoard').addEventListener('click',e=>{const b=e.target.closest('[data-cell]');if(!b||ultimate.turn!=='X'||ultimate.winner||settlements.ultimate)return;try{if(!ultimateMoves(ultimate).some(m=>m.board===Number(b.dataset.ultimateBoard)&&m.cell===Number(b.dataset.cell))||!clockMove('ultimate','you'))return;ultimate=ultimateMove(ultimate,Number(b.dataset.ultimateBoard),Number(b.dataset.cell));}catch{return;}renderUltimate();save();if(!ultimate.winner)botUltimate();});
/* A single private snapshot, serialized on every turn; no server or shared board. */
function snapshot(){return structuredClone({version:SAVE_VERSION,savedAt:Date.now(),active,tokens,paid:roundPaid,clocks,settlements,games:{chess:{pgn:chess.pgn(),lastMove,promotion,selected},cards:{deck,yourHand,botHand,phase:cardPhase,status:$('cardStatus').textContent},pens:{pens,turn:penTurn,phase:penPhase,result:penResult,shots,angle:$('penAngle').value,power:$('penPower').value,status:$('penStatus').textContent},rps,cricket,ultimate}});}
function save(quiet=false){if(!hydrated)return;updateTurn();const data=snapshot();try{localStorage.setItem('shri-private-playroom-recovery',JSON.stringify(data));}catch{}if(!quiet)$('playSaveStatus').textContent='Saving privately…';saveQueue=saveQueue.catch(()=>{}).then(()=>store.write(data)).then(()=>{if(!quiet)$('playSaveStatus').textContent='Saved privately · resume here anytime';}).catch(()=>{let recovery=false;try{recovery=!!localStorage.getItem('shri-private-playroom-recovery');}catch{}$('playSaveStatus').textContent=recovery?'Saved privately in this browser':'Browser storage unavailable · this session only';});}
function restore(data){
 if(validClock(data.clocks?.chess))clocks.chess=data.clocks.chess;
 for(const g of GAME_IDS){if(['you','bot','draw'].includes(data.settlements?.[g]?.result)&&!(g!=='chess'&&data.settlements[g].reason==='timeout'))settlements[g]=data.settlements[g];}
 tokens=data.tokens;roundPaid={...roundPaid,...data.paid};active=data.active;for(const g of GAME_IDS)if(g!=='chess'&&data.settlements?.[g]?.reason==='timeout')roundPaid[g]=false;
 for(const g of GAME_IDS){const v=data.games[g];if(!v)continue;try{
 if(g==='chess'){const restored=new Chess();if(v.pgn)restored.loadPgn(v.pgn);chess=restored;lastMove=v.lastMove;promotion=v.promotion;selected=v.selected;}
 if(g==='cards'&&['you','bot','over'].includes(v.phase)&&Array.isArray(v.deck)&&v.yourHand.length>=2&&v.botHand.length>=2){deck=v.deck;yourHand=v.yourHand;botHand=v.botHand;cardPhase=v.phase;$('cardStatus').textContent=v.status;}
 if(g==='pens'&&['ready','moving','over'].includes(v.phase)&&['you','bot'].includes(v.turn)&&v.pens.length===2&&v.pens.every(p=>['x','y','a','vx','vy','w'].every(k=>Number.isFinite(p[k])))){pens=v.pens;penTurn=v.turn;penPhase=v.phase;penResult=penResultFromSave(v);shots=v.shots;$('penAngle').value=v.angle;$('penPower').value=v.power;$('penStatus').textContent=v.status;$('penFlick').disabled=penPhase!=='ready'||penTurn!=='you';}
 if(g==='rps'&&['ready','reveal','over'].includes(v.phase)&&Number.isInteger(v.you)&&Number.isInteger(v.bot)&&(v.phase==='over'||RPS_CHOICES.includes(v.secret))&&(v.phase!=='reveal'||RPS_CHOICES.includes(v.pending)))rps=v;
 if(g==='cricket'&&['ready','ball','over'].includes(v.phase)&&[1,2].includes(v.innings)&&Number.isInteger(v.you)&&Number.isInteger(v.bot)&&(v.phase==='over'||Number.isInteger(v.secret))&&(v.phase!=='ball'||Number.isInteger(v.pending)))cricket=v;
 if(g==='ultimate'&&v.cells.length===9&&v.cells.every(c=>c.length===9&&c.every(x=>[null,'X','O'].includes(x)))&&v.boards.length===9&&['X','O'].includes(v.turn)){ultimate=v;}
 }catch{/* Keep the fresh round if an older or damaged game cannot be restored. */}}
}
open.disabled=true;resetChess();resetCards();resetPens();resetRps();resetCricket();resetUltimate();
let recovered=null;try{recovered=validSave(JSON.parse(localStorage.getItem('shri-private-playroom-recovery')));}catch{}
try{const stored=await store.read(),data=recovered&&(!stored||recovered.savedAt>=stored.savedAt)?recovered:stored;if(data)restore(data);}catch{if(recovered)restore(recovered);$('playSaveStatus').textContent='Browser storage unavailable · this session only';}
hydrated=true;showTokens();switchGame(active);renderCards();renderRps();renderCricket();renderUltimate();open.disabled=false;save();
window.addEventListener('pagehide',()=>save(true));

/* Per-player blitz clocks. Only the open, visible game's thinking time counts. */
function clockState(){return {done:!!settlements.chess,turn:chess.turn()};}
function stopGameControls(game){const panel=$('panel'+game[0].toUpperCase()+game.slice(1));panel.querySelectorAll('[data-square],[data-promote],[data-cell],[data-rps],[data-cricket],#cardHit,#cardStand,#penFlick,#chessDraw,#chessResign').forEach(b=>b.disabled=true);if(game==='chess'){$('chessResignConfirm').hidden=true;$('chessPromotion').hidden=true;}if(game===active){cancelPending();cancelAnimationFrame(penRaf);penRaf=0;aim=null;renderClock();}}
function renderSavedGame(game){if(game==='chess')renderChess();if(game==='cards')renderCards();if(game==='pens')drawPens();if(game==='rps')renderRps();if(game==='cricket')renderCricket();if(game==='ultimate')renderUltimate();}
function settleClock(){const now=performance.now(),elapsed=clockLast?now-clockLast:0;clockLast=now;if(!hydrated||!dialog.open||document.hidden||clockSettling||active!=='chess')return;const side=clockTurn(active,clockState(active)),step=advanceClock(clocks[active],side,elapsed);clocks[active]=step.clock;if(step.flagged){clockSettling=true;finish(active,active==='chess'?chessTimeoutResult(chess,step.flagged):step.flagged==='you'?'bot':'you','timeout');clockSettling=false;}renderClock();}
function clockMove(game,side){if(game!=='chess')return !settlements[game];settleClock();if(settlements[game])return false;clocks[game]=completeClockMove(clocks[game],side);clockLast=performance.now();return true;}
function renderClock(){dialog.dataset.game=active;dialog.querySelector('.play-clockbar').hidden=active!=='chess';dialog.querySelector('.clock-pause-note').hidden=active!=='chess';if(active!=='chess')return;const c=clocks.chess,side=dialog.open&&!document.hidden?clockTurn(active,clockState(active)):null;$('yourClock').textContent=c.enabled?formatClock(c.you):'—';$('botClock').textContent=c.enabled?formatClock(c.bot):'—';for(const who of ['you','bot']){const box=$(who==='you'?'yourClockWrap':'botClockWrap');box.classList.toggle('is-running',c.enabled&&side===who);box.classList.toggle('is-low',c.enabled&&c[who]<=30000);}$('gameClockMode').setAttribute('aria-pressed',String(c.enabled));$('gameClockMode').removeAttribute('aria-label');$('gameClockMode').setAttribute('title',c.enabled?'3 + 2, 3 min, +2 sec per move. Switch to untimed':'No clock. Untimed, take your time. Switch to 3 plus 2 clocks');$('gameClockMode').querySelector('strong').textContent=c.enabled?'3 + 2':'No clock';$('clockModeLabel').textContent=c.enabled?'3 min · +2 sec per move':'Untimed · take your time';}
$('gameClockMode').addEventListener('click',()=>{settleClock();clocks[active].enabled=!clocks[active].enabled;renderClock();save();});
setInterval(()=>{if(!hydrated||!dialog.open||document.hidden||active!=='chess')return;settleClock();if(performance.now()-clockPersist>1000&&!settlements[active]){clockPersist=performance.now();save(true);}},100);
$('chessDraw').addEventListener('click',()=>{if(settlements.chess)return;settleClock();if(settlements.chess)return;selected=promotion=null;$('chessStatus').textContent='Shri accepts your draw. Good game.';finish('chess','draw','agreed');});
$('chessResign').addEventListener('click',()=>{if(settlements.chess)return;$('chessResignConfirm').hidden=false;$('chessResignNo').focus();});
$('chessResignNo').addEventListener('click',()=>{$('chessResignConfirm').hidden=true;$('chessResign').focus();});
$('chessResignYes').addEventListener('click',()=>{if(settlements.chess)return;settleClock();if(settlements.chess)return;selected=promotion=null;$('chessStatus').textContent='You resigned. Shri wins.';finish('chess','bot','resigned');});
$('ultimateBoard').addEventListener('keydown',e=>{const b=e.target.closest('[data-cell]'),delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!b||!delta)return;e.preventDefault();const board=Number(b.dataset.ultimateBoard),cell=Number(b.dataset.cell);let x=(board%3)*3+cell%3,y=Math.floor(board/3)*3+Math.floor(cell/3);for(let i=0;i<9;i++){x+=delta[0];y+=delta[1];if(x<0||x>8||y<0||y>8)break;const target=$('ultimateBoard').querySelector(`[data-ultimate-board="${Math.floor(y/3)*3+Math.floor(x/3)}"][data-cell="${(y%3)*3+x%3}"]`);if(target&&!target.disabled){target.focus();break;}}});
