#!/usr/bin/env python3
"""
Rasterize a case-study PDF into the WebP screens the in-page viewer uses,
and write the result into js/cases-data.js (window.CASE_PAGES).

This handles the part of adding a new UI/UX case study that actually needs
code: turning a PDF into images. The rest (title, tags, blurb, thumbnail,
which PDF, and any prototype link) is a plain object you add by hand to
js/site-data.js — see the comment at the top of that file.

Usage:
    python3 tools/add_case_study.py <path-to.pdf> <slug> --layout deck
    python3 tools/add_case_study.py <path-to.pdf> <slug> --layout page

  --layout deck   separate framed slides (use for pitch-deck-style PDFs)
  --layout page   one continuous scroll (use for tall single-page site mockups)

Optional:
  --width N            target render width in px (default: 1600 for deck, 1400 for page)
  --tile-height N       max height per image before a tall page gets sliced into
                        multiple stacked tiles (default: 3600)
  --quality N           WebP quality (default: 82)
  --prototype-url URL   force the prototype link instead of auto-detecting one

Requires: pip install --user pymupdf pillow
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("Missing dependency. Run: pip install --user pymupdf pillow")
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CASES_DATA = ROOT / "js" / "cases-data.js"
PROTO_DOMAINS = ("figma.com/proto", "framer.com", "invisionapp.com", "proto.io")


def find_prototype_url(doc):
    found = []
    for page in doc:
        for link in page.get_links():
            uri = link.get("uri")
            if uri:
                found.append(uri)
    for uri in found:
        if any(d in uri.lower() for d in PROTO_DOMAINS):
            return uri, found
    return None, found


def render_page(page, target_width, tile_height, quality, out_dir, page_no):
    zoom = target_width / page.rect.width
    pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom))
    img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

    pages = []
    if pix.height <= tile_height:
        name = f"p{page_no:02d}.webp"
        img.save(out_dir / name, "WEBP", quality=quality)
        pages.append({"src": f"assets/cases/{out_dir.name}/{name}", "w": img.width, "h": img.height})
    else:
        n_tiles = -(-pix.height // tile_height)  # ceil
        tile_h = -(-pix.height // n_tiles)        # even-ish split
        for t in range(n_tiles):
            top = t * tile_h
            bottom = min(pix.height, top + tile_h)
            tile = img.crop((0, top, img.width, bottom))
            name = f"p{page_no:02d}_{t + 1:02d}.webp"
            tile.save(out_dir / name, "WEBP", quality=quality)
            pages.append({"src": f"assets/cases/{out_dir.name}/{name}", "w": tile.width, "h": tile.height})
    return pages


def update_cases_data(slug, layout, pages):
    if CASES_DATA.exists():
        content = CASES_DATA.read_text()
        m = re.search(r"window\.CASE_PAGES\s*=\s*(\{.*\});", content, re.S)
        data = json.loads(m.group(1)) if m else {}
    else:
        data = {}
    data[slug] = {"layout": layout, "pages": pages}
    header = (
        "/* AUTO-GENERATED by tools/add_case_study.py — do not hand-edit.\n"
        "   Per-slug rendered case-study screens: { layout, pages: [{src,w,h}] }.\n"
        "   Card metadata (title/tags/blurb/thumb/prototypeUrl) lives in js/site-data.js instead.\n"
        "   Re-run the tool for a slug to regenerate its entry here. */\n"
    )
    CASES_DATA.write_text(header + "window.CASE_PAGES = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pdf", type=Path)
    ap.add_argument("slug")
    ap.add_argument("--layout", choices=["deck", "page"], required=True)
    ap.add_argument("--width", type=int, default=None)
    ap.add_argument("--tile-height", type=int, default=3600)
    ap.add_argument("--quality", type=int, default=82)
    ap.add_argument("--prototype-url", default=None)
    args = ap.parse_args()

    if not args.pdf.exists():
        sys.exit(f"No such file: {args.pdf}")
    target_width = args.width or (1600 if args.layout == "deck" else 1400)

    dest_pdf = ROOT / "assets" / "pdfs" / f"{args.slug}.pdf"
    if args.pdf.resolve() != dest_pdf.resolve():
        dest_pdf.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(args.pdf, dest_pdf)
        print(f"copied PDF -> {dest_pdf.relative_to(ROOT)}")

    doc = fitz.open(dest_pdf)
    out_dir = ROOT / "assets" / "cases" / args.slug
    out_dir.mkdir(parents=True, exist_ok=True)

    all_pages = []
    for i, page in enumerate(doc):
        all_pages.extend(render_page(page, target_width, args.tile_height, args.quality, out_dir, i + 1))
    update_cases_data(args.slug, args.layout, all_pages)
    print(f"rendered {len(doc)} PDF page(s) -> {len(all_pages)} image(s) in {out_dir.relative_to(ROOT)}")
    print(f"updated {CASES_DATA.relative_to(ROOT)} for slug '{args.slug}'")

    proto_url = args.prototype_url
    auto_found, all_links = (None, [])
    if not proto_url:
        auto_found, all_links = find_prototype_url(doc)
        proto_url = auto_found

    print("\nNow add (or update) the matching entry in js/site-data.js -> SITE_DATA.work:\n")
    snippet = (
        f'    {{ slug: "{args.slug}", title: "TODO", tags: "TODO",\n'
        f'      blurb: "TODO",\n'
        f'      thumb: "assets/work/TODO.png", pdf: "assets/pdfs/{args.slug}.pdf"'
    )
    if proto_url:
        snippet += f',\n      prototypeUrl: "{proto_url}"'
    snippet += " },"
    print(snippet)

    if auto_found:
        print(f"\n(auto-detected prototype link: {auto_found})")
    elif all_links:
        print(f"\nNo obvious prototype link auto-detected, but found these link(s) in the PDF — "
              f"pass one with --prototype-url if one of them is the prototype:")
        for u in all_links:
            print(f"  - {u}")


if __name__ == "__main__":
    main()
